# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRVe31gu0kAe-CQVC7t4hqBF2MTFDn44
"""

import os
import pandas as pd
from etl.utils import log
from etl.utils import log, ensure_dir

def load_to_staging(df, config):
    staging_dir = config["paths"]["staging"]
    ensure_dir(staging_dir)
    path = os.path.join(staging_dir, "staging_clean.csv")

    df.to_csv(path, index=False)
    log(f"File loaded to STAGING: {path}")

    return path


def load_to_curated(df, config):
    curated_dir = config["paths"]["curated"]
    ensure_dir(curated_dir)
    path = os.path.join(curated_dir, "curated_final.csv")

    df.to_csv(path, index=False)
    log(f"File loaded to CURATED: {path}")

    return path