# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-RxFsK9v2FV6MM9APgYuMvTdCyhHdTn5
"""

import os
import json
import yaml
import hashlib
from datetime import datetime


def load_config(path="wildfire-data-pipeline\config\config.yaml"):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def ensure_dir(path):
    os.makedirs(path, exist_ok=True)

def log(msg):
    # === Format Log ===
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted = f"[LOG {timestamp}] {msg}"

    # === Ensure logs directory ===
    log_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "logs")
    os.makedirs(log_dir, exist_ok=True)

    # === Save log ===
    log_file = os.path.join(log_dir, "pipeline.log")
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(formatted + "\n")

    # === Print to console ===
    print(formatted)

def compute_hash(file_path):
    sha = hashlib.sha256()
    with open(file_path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            sha.update(chunk)
    return sha.hexdigest()