# -*- coding: utf-8 -*-
"""transform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cBoUq0lt9WvkZ--oD4zpv7uNbz9IMmTV
"""

import pandas as pd
from etl.utils import log

def transform_dataset(df):
    log("Inicializing transformations...")

    # Example of transformations:
    df.columns = df.columns.str.lower().str.replace(" ", "_")

    # Convert date columns
    if "fecha" in df.columns:
        df["fecha"] = pd.to_datetime(df["fecha"], errors="coerce")

    log("Transformations completed.")
    return df