# -*- coding: utf-8 -*-
"""qa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uA6G4ZWjBlq2wiPJa2-Tyl11fGdW-Hbu
"""

# ADVANCED QA CHECKS
# ====================================================

import pandas as pd
from etl.utils import log

def qa_checks(df):
    log("Executing QA...")

    # Separate types
    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
    categorical_cols = df.select_dtypes(include=["object"]).columns

    results = {
        "shape": df.shape,

        # NULLS
        "nulls": df.isnull().sum().to_dict(),

        # DUPLICATES
        "duplicates": int(df.duplicated().sum()),

        # NUMERIC VALUES
        "negative_values": (df[numeric_cols] < 0).sum().to_dict(),

        # RANGES
        "numeric_ranges": df[numeric_cols].describe(
            percentiles=[0.01, 0.05, 0.95, 0.99]
        ).T.to_dict(),

        # FREQS FOR CATEGORICAL 
        "categorical_top_values": {
            col: df[col].value_counts(dropna=False).head(5).to_dict()
            for col in categorical_cols
        }
    }

    log("QA completed.")
    return results